ALTER SCHEMA pgn TRANSFER dbo.pgn_archive
ALTER SCHEMA pgn TRANSFER dbo.pgn_archive_drivers
ALTER SCHEMA pgn TRANSFER dbo.pgn_archive_tractors
ALTER SCHEMA pgn TRANSFER dbo.pgn_archive_trailers
ALTER SCHEMA pgn TRANSFER dbo.pgn_breaks
ALTER SCHEMA pgn TRANSFER dbo.pgn_calls
ALTER SCHEMA pgn TRANSFER dbo.pgn_canbus
ALTER SCHEMA pgn TRANSFER dbo.pgn_customers
ALTER SCHEMA pgn TRANSFER dbo.pgn_depots
ALTER SCHEMA pgn TRANSFER dbo.pgn_drivers
ALTER SCHEMA pgn TRANSFER dbo.pgn_estimated_breaks
ALTER SCHEMA pgn TRANSFER dbo.pgn_routes
ALTER SCHEMA pgn TRANSFER dbo.pgn_shifts
ALTER SCHEMA pgn TRANSFER dbo.pgn_tractors
ALTER SCHEMA pgn TRANSFER dbo.pgn_trailers
ALTER SCHEMA pgn TRANSFER dbo.pgn_trips
ALTER SCHEMA pgn TRANSFER dbo.pgn_units

ALTER SCHEMA met TRANSFER dbo.met_dim_booking_detail
ALTER SCHEMA met TRANSFER dbo.met_dim_client
ALTER SCHEMA met TRANSFER dbo.met_dim_client_detail
ALTER SCHEMA met TRANSFER dbo.met_dim_collection
ALTER SCHEMA met TRANSFER dbo.met_dim_collection_detail
ALTER SCHEMA met TRANSFER dbo.met_dim_delivery
ALTER SCHEMA met TRANSFER dbo.met_dim_delivery_detail
ALTER SCHEMA met TRANSFER dbo.met_dim_driver
ALTER SCHEMA met TRANSFER dbo.met_dim_driver_detail
ALTER SCHEMA met TRANSFER dbo.met_dim_exception_detail
ALTER SCHEMA met TRANSFER dbo.met_dim_job_detail
ALTER SCHEMA met TRANSFER dbo.met_fact_invoices
ALTER SCHEMA met TRANSFER dbo.met_fact_orders
						  
ALTER SCHEMA mic TRANSFER dbo.mic_dim_comment_detail
ALTER SCHEMA mic TRANSFER dbo.mic_dim_haulier
ALTER SCHEMA mic TRANSFER dbo.mic_dim_journey
ALTER SCHEMA mic TRANSFER dbo.mic_dim_journey_detail
ALTER SCHEMA mic TRANSFER dbo.mic_dim_resource
ALTER SCHEMA mic TRANSFER dbo.mic_dim_resource_detail
ALTER SCHEMA mic TRANSFER dbo.mic_dim_site
ALTER SCHEMA mic TRANSFER dbo.mic_dim_site_detail
ALTER SCHEMA mic TRANSFER dbo.mic_fact_distance_actual
ALTER SCHEMA mic TRANSFER dbo.mic_fact_distance_planned
						  
ALTER SCHEMA cez TRANSFER dbo.cez_absence_type_reasons
ALTER SCHEMA cez TRANSFER dbo.cez_absence_type_reasons_picklist
ALTER SCHEMA cez TRANSFER dbo.cez_absence_type_reasons_translations
ALTER SCHEMA cez TRANSFER dbo.cez_absence_type_translations
ALTER SCHEMA cez TRANSFER dbo.cez_absence_types
ALTER SCHEMA cez TRANSFER dbo.cez_addresses
ALTER SCHEMA cez TRANSFER dbo.cez_adjustments
ALTER SCHEMA cez TRANSFER dbo.cez_bankdetails
ALTER SCHEMA cez TRANSFER dbo.cez_beneficiaries
ALTER SCHEMA cez TRANSFER dbo.cez_benefits
ALTER SCHEMA cez TRANSFER dbo.cez_calendar_assigment
ALTER SCHEMA cez TRANSFER dbo.cez_calendar_events_orgunit
ALTER SCHEMA cez TRANSFER dbo.cez_calendar_events_person
ALTER SCHEMA cez TRANSFER dbo.cez_clockinoutdetils
ALTER SCHEMA cez TRANSFER dbo.cez_communications
ALTER SCHEMA cez TRANSFER dbo.cez_companyattributes
ALTER SCHEMA cez TRANSFER dbo.cez_companydetails
ALTER SCHEMA cez TRANSFER dbo.cez_compensation
ALTER SCHEMA cez TRANSFER dbo.cez_costcentredeployments
ALTER SCHEMA cez TRANSFER dbo.cez_costcentres
ALTER SCHEMA cez TRANSFER dbo.cez_deleted_absence_events
ALTER SCHEMA cez TRANSFER dbo.cez_dependants
ALTER SCHEMA cez TRANSFER dbo.cez_disabilities
ALTER SCHEMA cez TRANSFER dbo.cez_education
ALTER SCHEMA cez TRANSFER dbo.cez_emergencycontacts
ALTER SCHEMA cez TRANSFER dbo.cez_employeewtp
ALTER SCHEMA cez TRANSFER dbo.cez_employeewtpdetails
ALTER SCHEMA cez TRANSFER dbo.cez_employeewtpfte
ALTER SCHEMA cez TRANSFER dbo.cez_employments
ALTER SCHEMA cez TRANSFER dbo.cez_empoyment_contracts
ALTER SCHEMA cez TRANSFER dbo.cez_inventoryassigment
ALTER SCHEMA cez TRANSFER dbo.cez_inventoryitmes
ALTER SCHEMA cez TRANSFER dbo.cez_job_deployments
ALTER SCHEMA cez TRANSFER dbo.cez_jobattributes
ALTER SCHEMA cez TRANSFER dbo.cez_jobs
ALTER SCHEMA cez TRANSFER dbo.cez_languageskills
ALTER SCHEMA cez TRANSFER dbo.cez_legal_identifiers
ALTER SCHEMA cez TRANSFER dbo.cez_location_deployments
ALTER SCHEMA cez TRANSFER dbo.cez_maritalstatus
ALTER SCHEMA cez TRANSFER dbo.cez_org_unit_position_deployments
ALTER SCHEMA cez TRANSFER dbo.cez_orgunits
ALTER SCHEMA cez TRANSFER dbo.cez_peoples
ALTER SCHEMA cez TRANSFER dbo.cez_person_absence_events
ALTER SCHEMA cez TRANSFER dbo.cez_person_reports_to
ALTER SCHEMA cez TRANSFER dbo.cez_person_timesheet_activities
ALTER SCHEMA cez TRANSFER dbo.cez_person_timesheet_settings
ALTER SCHEMA cez TRANSFER dbo.cez_person_timesheet_timesheetsplans
ALTER SCHEMA cez TRANSFER dbo.cez_position_details
ALTER SCHEMA cez TRANSFER dbo.cez_positionattributes
ALTER SCHEMA cez TRANSFER dbo.cez_positiongrades
ALTER SCHEMA cez TRANSFER dbo.cez_presonal_development
ALTER SCHEMA cez TRANSFER dbo.cez_project_activities
ALTER SCHEMA cez TRANSFER dbo.cez_project_activitytimetypes
ALTER SCHEMA cez TRANSFER dbo.cez_projects
ALTER SCHEMA cez TRANSFER dbo.cez_time_off_in_lieu
ALTER SCHEMA cez TRANSFER dbo.cez_visadetails
ALTER SCHEMA cez TRANSFER dbo.cez_workspaces
						  
ALTER SCHEMA ahp TRANSFER dbo.delivery
ALTER SCHEMA ahp TRANSFER dbo.patients
ALTER SCHEMA ahp TRANSFER dbo.comments
ALTER SCHEMA ahp TRANSFER dbo.status
ALTER SCHEMA ahp TRANSFER dbo.activity
ALTER SCHEMA ahp TRANSFER dbo.adherepredict
ALTER SCHEMA ahp TRANSFER dbo.failures